apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: event-dispatcher
spec:
  replicas: 1
  template:
    metadata:
      name: event-dispatcher
      labels:
        app: event-dispatcher
    spec:
      containers:
      - image: sk8s/event-dispatcher:0.0.1-SNAPSHOT
        name: event-dispatcher
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /application/status
            port: 8080
          initialDelaySeconds: 90
          periodSeconds: 15
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /application/status
            port: 8080
          initialDelaySeconds: 20
          periodSeconds: 15
          timeoutSeconds: 5
        env:
        - name: JAVA_TOOL_OPTIONS
          value: '-Xmx512m'
        - name: SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS
          value: kafka:9092
        - name: SPRING_CLOUD_STREAM_KAFKA_BINDER_ZKNODES
          value: zookeeper:2181
